### ISSUE TITLE
Resizing of app is very slow

### ISSUE THREAD

**Issue by yash1200** [caoxiemeihao/vite-react-electron#17]
I cloned the project, and tested it for performance and other stuff, the things that's slow here is resizing of the app. I tried this last month too and it was working fine, Maybe some changes in the past weeks broke something. Here's a screenshot for the same.
This is on the production build.

![Screenshot 2022-02-12 at 4 09 00 PM](https://user-images.githubusercontent.com/38391570/153708006-57ec9616-d1ca-4ddc-acb8-0a19cbe3599b.png)

**Comment by caoxiemeihao** [comment]
Thank you feedback.
I tried to go back to last month's version, but I didn't see that it would run faster.
If you can remember the approximate date, I'll compare the code at that time.
Maybe I really inadvertently caused this problem.

**Comment by yash1200** [comment]
I don't remember the date, but it was around at the starting of January.

**Comment by yash1200** [comment]
Also this error comes after I made some changes in the app.
`
SyntaxError: The requested module '/@fs/Users/yashjohri/Projects/Vite/node_modules/.vite-plugin-resolve/electron.js' does not provide an export named 'remote'
`

**Comment by caoxiemeihao** [comment]
> Also this error comes after I made some changes in the app. `SyntaxError: The requested module '/@fs/Users/yashjohri/Projects/Vite/node_modules/.vite-plugin-resolve/electron.js' does not provide an export named 'remote'`

Can you post your modified relevant code?  

In fact, `remote` has been deprecated in `electron`. If you still use it in you  App.  
You can export `remote` in `renderer/vite.config.ts`  

https://github.com/caoxiemeihao/vite-react-electron/blob/a6c9cad8d011348f503068a3375222a32e76a45b/packages/renderer/vite.config.ts#L66

```diff
const electron = require("electron");
const {
  clipboard,
  nativeImage,
  shell,
  contextBridge,
  crashReporter,
  ipcRenderer,
  webFrame,
  desktopCapturer,
  deprecate,
+ remote,
} = electron;

export {
  electron as default,
  clipboard,
  nativeImage,
  shell,
  contextBridge,
  crashReporter,
  ipcRenderer,
  webFrame,
  desktopCapturer,
  deprecate,
+ remote,
}
```
