### ISSUE TITLE
大佬，请问怎么使用fetch

### ISSUE THREAD

**Issue by Qi728** [caoxiemeihao/vite-react-electron#20]
![image](https://user-images.githubusercontent.com/71055096/155878255-8f8b0da4-1ce5-47f9-8c04-2d9e737c51ff.png)

**Comment by caoxiemeihao** [comment]
你放到 dependenices 中试试

**Comment by caoxiemeihao** [comment]
拉下最新代码即可，现在已经支持 node-fetch 这种纯 ESM 包了
有兴趣可以研究下这个文件
https://github.com/caoxiemeihao/vite-react-electron/blob/main/scripts/vite-plugin-esm2cjs.ts

**Comment by Qi728** [comment]
> 拉下最新代码即可，现在已经支持 execa、node-fetch 这种纯 ESM 包了 有兴趣可以研究下这个文件 https://github.com/caoxiemeihao/vite-react-electron/blob/main/scripts/vite-plugin-esm2cjs.ts

好的 谢谢大哥
