### ISSUE TITLE
[Help] dmg 已损坏，无法打开。 你应该将它移到废纸篓

### ISSUE THREAD

**Issue by zengtiansheng** [caoxiemeihao/vite-react-electron#234]
使用github Actions 构建出的产物无法安装使用。
包括该仓库下本身构建出的资源 [https://github.com/electron-vite/electron-vite-react/actions/runs/11878505364](https://github.com/electron-vite/electron-vite-react/actions/runs/11878505364)

![image](https://github.com/user-attachments/assets/d4f80913-375a-4bf7-b65a-1be7b58ba952)

![image](https://github.com/user-attachments/assets/00dc7ed4-c62a-4870-9e80-ee4c183aeab8)

> 本地环境：macos Sequoia 15.1  M1

**Comment by ashen114** [comment]
要避免这种提示，你需要先[签名](https://www.electron.build/code-signing)；
需要打开这类未签名的app，可以在“隐私与安全”那边允许运行这个app

**Comment by zengtiansheng** [comment]
@ashen114 隐私与安全我开启了【任何来源】貌似也没用
![image](https://github.com/user-attachments/assets/16a62fb7-a5df-4b40-a900-0c6d564eb64b)

**Comment by zengtiansheng** [comment]
感谢 @ashen114 ， 确实是签名的问题，我macos升级了新系统，安装未签名需要对应用执行 `sudo xattr -dr com.apple.quarantine` 命令
https://sysin.org/blog/macos-if-crashes-when-opening/
