### ISSUE TITLE
Support for vscode debug mode

### ISSUE THREAD

**Issue by Hacksore** [caoxiemeihao/vite-react-electron#4]
Add VSCode debug launch/tasks for both of the following to help make setting break points a possiblity.

- React
- Electron

**Comment by caoxiemeihao** [comment]
This is a good suggestion.

**Comment by caoxiemeihao** [comment]
README.md has added description. [Use Electron, NodeJs API](https://github.com/caoxiemeihao/electron-vue-vite#use-electron-nodejs-api)

**Comment by andrewcartwright1** [comment]
Yes please, would like to see this!

**Comment by CallanBi** [comment]
同样的 issue。/ Same issue.

希望 main 支持 Chrome inspector 或 VScode 调试 / Wanting support for Chrome inspector or VScode debugging mode in the main process.

十分感谢。/ Really appreciate it if it is being added.

**Comment by CallanBi** [comment]
@Hacksore @andrewcartwright1 I just commit a PR that supports debugging in VSCode in the main process. See if it works for you :) [PR](https://github.com/caoxiemeihao/vite-react-electron/pull/18)

**Comment by Hacksore** [comment]
I still think we might want to include debugging for react with this issue, thoughts?
