### ISSUE TITLE
 npm run dev and some error

### ISSUE THREAD

**Issue by wzskyline** [caoxiemeihao/vite-react-electron#6]
$ npm run dev
 
> node scripts/watch.mjs

file://vite-react-electron-main/scripts/watch.mjs:6
import { createServer, build as viteBuild } from 'vite'
                       ^^^^^
SyntaxError: The requested module 'vite' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'vite';

**Comment by caoxiemeihao** [comment]
node version must be >= "14.7.0"
