### ISSUE TITLE
Imports from electron

### ISSUE THREAD

**Issue by PAXANDDOS** [caoxiemeihao/vite-react-electron#7]
Hi! First of all, I'm new to Electron and its ecosystem, but your Vite-React boilerplate is the best I found so far, love it! ❤️ 

I've got stuck importing stuff from electron. For example:
```tsx
// src/renderer/src/App.tsx

import { clipboard } from "electron"

function App() {
	const addToClipboard = () => {
		clipboard.writeText("Example String", "selection")
		console.log(clipboard.readText("selection"))
	}

	return (
		<div className='App'>
			<button onClick={addToClipboard}>Click me</button>
		</div>
	)
}

export default App

```

And I only get this error in the console:
```js
Uncaught ReferenceError: require is not defined at electron.js:5
```

Also to mention, there are a few errors in the terminal which appears after running `npm run dev`:
```bash
[0122/180339.314:ERROR:registration_protocol_win.cc(102)] CreateFile: ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы. (0x2)
[0122/180339.358:ERROR:registration_protocol_win.cc(102)] CreateFile: ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы. (0x2)
[14232:0122/180339.788:ERROR:CONSOLE(1)] "SyntaxError: Unexpected end of JSON input", source: devtools://devtools/bundled/entrypoints/main/main.js (1)
```
The first two of them are probably because I have the Russian language as the system default and it tries to create files with a Chinese name (?)

**I wonder if I'm doing something wrong or just missing something. Can you help me?**

Node v17.2.0
NPM v8.1.4
Windows 11 build 22000
```json
"devDependencies": {
      "@types/react": "^17.0.33",
      "@types/react-dom": "^17.0.10",
      "@vitejs/plugin-react": "^1.0.7",
      "electron": "^15.3.0",
      "electron-builder": "^22.13.1",
      "react": "^17.0.2",
      "react-dom": "^17.0.2",
      "typescript": "^4.4.4",
      "vite": "^2.6.13",
      "vite-plugin-resolve": "^1.3.1"
}
```

**Comment by caoxiemeihao** [comment]
1. First you need allow use `Electron` as `NodeJs` API in Renderer-prodess

https://github.com/caoxiemeihao/vite-react-electron/blob/8a9e5c2ab0b371be287afc8c16ad6563f162cabb/src/main/index.ts#L19

```diff
  win = new BrowserWindow({
    title: 'Main window',
    webPreferences: {
+      nodeIntegration: true,
+      contextIsolation: false,
      preload: join(__dirname, '../preload/index.cjs')
    },
  })
```

2. Second remove Preload-script `exposeInMainWorld` members

https://github.com/caoxiemeihao/vite-react-electron/blob/8a9e5c2ab0b371be287afc8c16ad6563f162cabb/src/preload/index.ts#L16

```diff
- contextBridge.exposeInMainWorld('fs', fs)
- contextBridge.exposeInMainWorld('removeLoading', removeLoading)
- contextBridge.exposeInMainWorld('ipcRenderer', withPrototype(ipcRenderer))
```

3. Third change Preload-scirpt adn Renderer-process common part

https://github.com/caoxiemeihao/vite-react-electron/blob/main/src/preload/index.ts

```diff
+ window.removeLoading = removeLoading

**Comment by PAXANDDOS** [comment]
That worked well, thanks! 🚀 

But I guess it's not the perfect solution, is it? Because of newly appeared warnings about security. If not importing from electron directly in component, is there any other way to access its features?
Also I guess removing ipcRenderer made the electron-store break as I can guess from this error message:

![image](https://user-images.githubusercontent.com/40315177/150772007-820870ef-a83e-44cc-8329-0b2ddbc502ea.png)

**Comment by caoxiemeihao** [comment]
```diff
- window.ipcRenderer

+ import { ipcRenderer } from 'electron'
+ ipcRenderer(/* something*/)
```

**Comment by PAXANDDOS** [comment]
Got it. Just in time, I learned how to throw emits to the main process via `ipcRenderer`. Now I understood the whole concept, thanks!
